version: '3.7'

services:
  wordpress:
    image: wordpress:6
    restart: always
    environment:
      WORDPRESS_DB_HOST: db 
      WORDPRESS_DB_USER: root 
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql-password
      WORDPRESS_DB_NAME: wordpress
    networks:
      public:
      wordpress:
    volumes:
      - wordpress:/var/www/html
    secrets:
      - mysql-password
    deploy:
      labels:
        traefik.http.routers.wordpress-michendorf.rule: Host(`michendorf.klima-daten.de`)
        traefik.http.routers.wordpress-michendorf.tls: "true"
        traefik.http.routers.wordpress-michendorf.tls.certresolver: default
        traefik.docker.network: public
        traefik.http.services.wordpress-michendorf.loadbalancer.server.port: 80
        traefik.enable: "true"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress 
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-password
    networks:
      public:
      wordpress:
    volumes:
      - db:/var/lib/mysql
    secrets:
      - mysql-password

secrets:
  mysql-password:
    external: true
    
networks:
  public:
    external: true
  wordpress:

volumes:
  wordpress:
  db:
