name: Docker Image CI

on:
  push:
    branches: [ release/michendorf ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: r.planetary-quantum.com/quantum-public/cli:2
    env:
      QUANTUM_USER: ${{ secrets.QUANTUM_USER }}
      QUANTUM_PASSWORD: ${{ secrets.QUANTUM_PASSWORD }}
      QUANTUM_ENDPOINT: "tpwd-klimadashboard"
      QUANTUM_STACK: "wordpress-michendorf"
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Planetary Quantum
        run: quantum-cli stacks update --create --wait
